server:
  port: 8079

spring:
  application:
    name: Apigateway
  cloud:
    gateway:
      routes:
        - id: docentes-evaluadores-service
          uri: http://localhost:8080
          predicates:
            - Path = /api/docentes/**
            - Path = /api/evaluadores**
          filters:
            - name: JwtAuthenticationFilter
        - id: login-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/login/**
        - id: rac-programa-asignatura-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/competenciasAsignatura/**
            - Path = /api/competenciasPrograma/**
            - Path = /api/RAAsignatura/**
            - Path = /api/RAPrograma/**
          filters:
            - name: JwtAuthenticationFilter
        - id: rubrica-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/rubrica/**
          filters:
            - name: JwtAuthenticationFilter  
        - id: curso-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/cursos/**
            - Path = /api/asignatura/**
          filters:
            - name: JwtAuthenticationFilter
  
