server:
  port: 8079

spring:
  application:
    name: Apigateway
  cloud:
    gateway:
      routes:
        - id: docentes-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/docentes/**
          filters:
            - name: JwtAuthenticationFilter
        - id: evaluadores-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/evaluadores/**
          filters:
            - name: JwtAuthenticationFilter
        - id: login-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/login/**
        - id: competencias-asignatura-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/competenciasAsignatura/**
          filters:
            - name: JwtAuthenticationFilter
        - id: competencias-programa-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/competenciasPrograma/**
          filters:
            - name: JwtAuthenticationFilter
        - id: ra-asignatura-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/RAAsignatura/**
          filters:
            - name: JwtAuthenticationFilter
        - id: ra-programa-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/RAPrograma/**
          filters:
            - name: JwtAuthenticationFilter
        - id: rubrica-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/rubricas/**
          filters:
            - name: JwtAuthenticationFilter  
        - id: curso-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/cursos/**
          filters:
            - name: JwtAuthenticationFilter
        - id: asignatura-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/asignatura/**
          filters:
            - name: JwtAuthenticationFilter
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
